routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Route::resource('/replay', 'ReplayController', ['only' => ['create', 'store', 'show']]);
Route::get('/replay/{replay}/download', 'ReplayController@download');

Route::resource('/course', 'CourseController', ['only' => ['index', 'show']]);

Route::group(['prefix' => '/admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	Route::get('/', function () {
		return view('pages.admin.index');
	});
	
	Route::resource('/course', 'CourseController');
	Route::resource('/replay', 'ReplayController');
});


Route::get('login', [
  'as' => 'login',
  'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('login', [
  'as' => '',
  'uses' => 'Auth\LoginController@login'
]);
Route::post('logout', [
  'as' => 'logout',
  'uses' => 'Auth\LoginController@logout'
]);

app/Models/Course.php
<?php namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * A course that replays compete for position on.
 *
 * @property string   $name    The name of the course.
 * @property Map[]    $maps    The maps that encompass this course.
 * @property Replay[] $replays All replays submitted for this course.
 */
class Course extends Model
{
	protected $no_skips;
	
	protected $fillable = ['name'];
	
	public function maps()
	{
		return $this->hasMany(Map::class);
	}
	
	public function replays()
	{
		return $this->hasManyThrough(Replay::class, Map::class);
	}
	
	public function getTimeLeaderboardAttribute()
	{
		return $this->leaderboard('race_tics');
	}
	
	public function getLapLeaderboardAttribute()
	{
		return $this->leaderboard('lap_tics');
	}
	
	protected function leaderboard($column)
	{
		$allReplays = $this->replays()
			->where(function ($query) {
				if ($this->no_skips) {
					$query->where('replays.status', Replay::STATUS_VERIFIED);
				} else {
					$query->whereIn('replays.status', Replay::LEADERBOARD_STATUSES);
				}
				
				$query->orWhereNull('replays.status');
			})->orderBy("replays.$column", 'asc')->get();
		
		$names = [];
		
		$replays = $allReplays->filter(function (Replay $replay) use (&$names) {
			if (in_array($replay->name, $names)) {
				return false;
			}
			
			$names[] = $replay->name;
			
			return true;
		});
		
		return $replays;
	}
	
	public function hideMajorSkips()
	{
		$this->no_skips = true;
		
		return $this;
	}
	
	public function scopeWithReplayCount($query, Carbon $since = null)
	{
		$query->select('courses.*', \DB::raw('COUNT(replays.id) as replay_count'))
			->leftJoin('maps', 'maps.course_id', '=', 'courses.id')
			->leftJoin('replays', 'replays.map_id', '=', 'maps.id')
			->groupBy('courses.id');
		
		if ($since) {
			$query->where('replays.created_at', '>', $since);
		}
	}
}

app/Models/Map.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Map extends Model
{
	protected $fillable = ['checksum', 'map_number'];
	
	public function course()
	{
		return $this->belongsTo(Course::class);
	}
	
	public function getMapTagAttribute()
	{
		$num = $this->map_number;
		
		if ($num < 100) {
			return sprintf('MAP%02d', $num);
		}
		
		$num -= 100;
		
		$second = $num % 36;
		$first = intval($num / 36);
		
		$first = chr(ord('A') + $first);
		
		if ($second > 9) {
			$second = chr(ord('A') + $second - 10);
		}
		
		return 'MAP' . $first . $second;
	}
}

app/Http/Controllers/Admin/CourseController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\{Course, Map};
use Illuminate\Http\Request;

class CourseController extends Controller
{
	public function index()
	{
		return view('pages.admin.course.index', ['courses' => Course::all()]);
	}
	
	public function create()
	{
		return $this->show(new Course());
	}
	
	public function store(Request $request)
	{
		return $this->update($request, new Course());
	}
	
	public function show(Course $course)
	{
		return view('pages.admin.course.show', ['course' => $course, 'freeMaps' => Map::doesntHave('course')->get()]);
	}
	
	public function update(Request $request, Course $course)
	{
		$course->fill($request->only('name'))->save();
		
		if (!empty($addMapId = $request->get('add_map'))) {
			Map::whereKey($addMapId)->update(['course_id' => $course->getKey()]);
		}
		
		if (!empty($removeMapIds = $request->get('remove_map'))) {
			Map::whereIn('id', $removeMapIds)->update(['course_id' => null]);
		}
		
		return redirect(action('Admin\CourseController@show', compact('course')));
	}
	
	public function destroy(Course $course)
	{
		$course->delete();
		
		return redirect(action('Admin\CourseController@index'));
	}
}

app/Http/Controllers/CourseController.php
<?php namespace App\Http\Controllers;

use App\Models\Course;
use Illuminate\Http\Request;

class CourseController extends Controller
{
	public function index()
	{
		return view('pages.course.index', ['courses' => Course::all()]);
	}
	
	public function show(Request $request, Course $course)
	{
		if (!($skips = $request->get('skips'))) {
			$course->hideMajorSkips();
		}
		
		return view('pages.course.show', ['course' => $course, 'skips' => $skips]);
	}
}

resources/views/pages/admin/course/index.blade.php
@extends('layouts.admin')

@section('content')
<h1>Courses</h1>

<ul>
@foreach($courses as $course)
	<li><a href="{{ action('Admin\CourseController@show', compact('course')) }}">{{ $course->name }}</a></li>
@endforeach
</ul>

<a href="{{ action('Admin\CourseController@create') }}">Add New Course</a>
@stop

resources/views/pages/admin/course/show.blade.php
@extends('layouts.admin')

@section('content')
<h1>{{ $course->exists ? 'Edit Course' : 'New Course' }}</h1>

<form action="{{ action('Admin\CourseController@' . ($course->exists ? 'update' : 'store'), compact('course')) }}" method="POST" enctype="multipart/form-data">
	{!! csrf_field() !!}
	@if($course->exists)
		<input type="hidden" name="_method" value="PUT" />
	@endif
	
	<label>
		Name:
		<input type="text" name="name" value="{{ $course->name }}" />
	</label>
	
	<label>
		Add Map:
		<select name="add_map">
			<option value="">-- Select --</option>
			@foreach($freeMaps as $map)
				<option value="{{ $map->getKey() }}">{{ $map->map_tag }} - {{ $map->checksum }}</option>
			@endforeach
		</select>
	</label>
	
	@if($course->exists)
		Remove Maps:
		@foreach($course->maps as $map)
			<label>
				<input type="checkbox" name="remove_map[]" value="{{ $map->getKey() }}" />
				{{ $map->map_tag }} - {{ $map->checksum }}
			</label>
		@endforeach
	@endif
	
	<input type="submit" value="Save" />
</form>

@if($course->exists)
	<form action="{{ action('Admin\CourseController@destroy', compact('course')) }}" method="POST">
		{!! csrf_field() !!}
		<input type="hidden" name="_method" value="DELETE" />
		<input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this course?')" />
	</form>
@endif
@stop