routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Route::resource('/replay', 'ReplayController', ['only' => ['create', 'store', 'show']]);
Route::get('/replay/{replay}/download', 'ReplayController@download');

Route::resource('/course', 'CourseController', ['only' => ['index', 'show']]);

Route::group(['prefix' => '/admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
	Route::get('/', function () {
		return view('pages.admin.index');
	});
	
	Route::resource('/course', 'CourseController');
	Route::resource('/replay', 'ReplayController');
});


Route::get('login', [
  'as' => 'login',
  'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('login', [
  'as' => '',
  'uses' => 'Auth\LoginController@login'
]);
Route::post('logout', [
  'as' => 'logout',
  'uses' => 'Auth\LoginController@logout'
]);

app/Models/Replay.php
<?php namespace App\Models;

use Illuminate\Contracts\Filesystem\Filesystem;
use Illuminate\Database\Eloquent\Model;

/**
 * An uploaded record attack replay.
 *
 * @property Map       $map       The specific variant of the course this replay was recorded on.
 * @property string    $name      The name of the player.
 * @property Character $character The character the player used.
 * @property string    $color     The color the player used on their character.
 * @property integer   $race_tics The total race time, in tics (1/35 seconds).
 * @property integer   $lap_tics  The best lap time, in tics (1/35 seconds).
 * @property string    $checksum  The MD5 hash of this replay.
 * @property string    $status    The admin-checked status of this replay.
 */
class Replay extends Model
{
	const STATUS_VERIFIED = 'Verified';
	const STATUS_MAJOR_SKIPS = 'Major Skips';
	const STATUS_HACKED = 'Hacked';
	const STATUS_HIDDEN = 'Hidden';
	
	const STATUSES = [
		self::STATUS_VERIFIED,
		self::STATUS_MAJOR_SKIPS,
		self::STATUS_HACKED,
		self::STATUS_HIDDEN,
	];
	
	const LEADERBOARD_STATUSES = [
		self::STATUS_VERIFIED,
		self::STATUS_MAJOR_SKIPS,
	];
	
	protected $fillable = ['name', 'color', 'race_tics', 'lap_tics', 'checksum', 'status'];
	
	public function course()
	{
		return $this->map->course();
	}
	
	public function map()
	{
		return $this->belongsTo(Map::class);
	}
	
	public function character()
	{
		return $this->belongsTo(Character::class);
	}
	
	public function getRaceTimeAttribute() : string
	{
		return $this->ticsToTime($this->race_tics);
	}
	
	public function getLapTimeAttribute() : string
	{
		return $this->ticsToTime($this->lap_tics);
	}
	
	protected function ticsToTime($tics) : string
	{
		$centiseconds = intval($tics * 100 / 35);
		$seconds = intval($tics/35);
		$minutes = intval($seconds / 60);
		
		return sprintf('%d\'%02d"%02d', $minutes, $seconds % 60, $centiseconds % 100);
	}
	
	public function getRaceRankAttribute() : string
	{
		return $this->rank('race_tics', 'time_leaderboard');
	}
	
	public function getLapRankAttribute() : string
	{
		return $this->rank('lap_tics', 'lap_leaderboard');
	}
	
	protected function rank($column, $leaderboard) : string
	{
		if (!$this->course) {
			return 'Unknown rank';
		}
		
		$betterTimes = $this->course->$leaderboard->filter(function (Replay $replay) use ($column) {
			return $replay->$column < $this->$column;
		})->count();
		
		$rank = $betterTimes + 1;
		
		if ($rank >= 10 && $rank < 20) {
			return $rank . 'th';
		}
		
		if ($rank % 10 == 1) {
			return $rank . 'st';
		}
		if ($rank % 10 == 2) {
			return $rank . 'nd';
		}
		if ($rank % 10 == 3) {
			return $rank . 'rd';
		}
		
		return $rank . 'th';
	}
	
	public function storeFile($data)
	{
		app(Filesystem::class)->put($this->getFilepath(), $data);
	}
	
	public function getFile() : string
	{
		return app(Filesystem::class)->get($this->getFilepath());
	}
	
	public function getFilepath() : string
	{
		return "replays/{$this->getKey()}";
	}
}

app/Http/Controllers/Admin/ReplayController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Replay;
use Illuminate\Http\Request;

class ReplayController extends Controller
{
	public function index(Request $request)
	{
		$query = Replay::query();
	
		if ($request->get('unchecked')) {
			$query->whereNull('status');
		}
	
		return view('pages.admin.replay.index', [
			'replays' => $query->paginate(25)->appends($request->only('unchecked')), 
			'statuses' => Replay::STATUSES
		]);
	}
	
	public function update(Request $request, Replay $replay)
	{
		$replay->update($request->only('status'));
		
		return redirect()->back();
	}
}

app/Http/Controllers/ReplayController.php
<?php namespace App\Http\Controllers;

use App\Exceptions\{ReplayDuplicationException, ReplayException};
use App\Models\Replay;
use App\Services\ReplayParser;
use Illuminate\Http\Request;
use Storage;

class ReplayController extends Controller
{
	public function create()
	{
		return view('pages.replay.create');
	}

	public function store(Request $request, ReplayParser $parser)
	{
		$replayFile = $request->file('replay');
		
		try {
			$replay = $parser->storeReplay($replayFile->get());
		} catch (ReplayDuplicationException $e) {
			return response($e->getMessage(), 409);
		} catch (ReplayException $e) {
			return response($e->getMessage(), 422);
		}
		
		return redirect(action('ReplayController@show', compact('replay')));
	}
	
	public function show(Replay $replay)
	{
		return view('pages.replay.show', compact('replay'));
	}
	
	public function download(Replay $replay)
	{
		return Storage::download($replay->getFilepath(), "{$replay->map->map_tag}-guest.lmp");
	}
}

resources/views/pages/replay/create.blade.php
@extends('layouts.front')

@section('content')
<h1>Upload Replay</h1>

<form action="{{ action('ReplayController@store') }}" method="POST" enctype="multipart/form-data">
	@csrf
	<label>
		Upload replay:
		<input type="file" name="replay" />
	</label>

	<input type="submit" value="Upload" />
</form>

<p id="replay_drop" ondrop="uploadReplaysHandler(event)" ondragover="event.preventDefault()">Or drag and drop replays here</div>

<script>
	function uploadReplaysHandler(event) {
		event.preventDefault();
		
		if (event.dataTransfer.items) {
			// Use DataTransferItemList interface to access the file(s)
			for (let i = 0; i < event.dataTransfer.items.length; i++) {
				// If dropped items aren't files, reject them
				if (event.dataTransfer.items[i].kind === 'file') {
					uploadReplay(event.dataTransfer.items[i].getAsFile());
				}
			}
		} else {
			// Use DataTransfer interface to access the file(s)
			for (let i = 0; i < event.dataTransfer.files.length; i++) {
				uploadReplay(event.dataTransfer.files[i]);
			}
		} 

		// Pass event to removeDragData for cleanup
		removeDragData(event)
	}
	
	function uploadReplay(file) {
		let url = {!! json_encode(action('ReplayController@store')) !!};
		let formData = new FormData();

		formData.append('_token', {!! json_encode(csrf_token()) !!});
		formData.append('replay', file);

		fetch(url, {
			method: 'POST',
			body: formData,
			credentials: 'include'
		})
		.then(function(response) {
			let result = 'Success';
			
			if (response.status == 422) {
				result = 'Failed';
			} else if (response.status == 409) {
				result = 'Already Exists';
			}
			
			showResult(file.name, result);
		})
		.catch(function() {
			showResult(file.name, 'Failed');
		});
	}
	
	function showResult(filename, result) {
		let el = document.createElement('p');
		el.innerText = filename + ': ';
		el.innerHTML += '<b>' + result + '</b>';
		
		document.getElementById('replay_drop').innerHTML += el.outerHTML;
	}
</script>
@stop

resources/views/pages/replay/show.blade.php
@extends('layouts.front')

@section('content')
<h1>View Replay</h1>

@if($replay->course)
	<p>On {{ $replay->course->name }}</p>
@else
	<p>On an unidentified course</p>
@endif

<p>Racer: {{ $replay->name }}</p>
<p>Character: {{ $replay->character->name ?: $replay->character->skin }}</p>
<p>Time: {{ $replay->race_time }} ({{ $replay->race_rank }})</p>
<p>Best Lap: {{ $replay->lap_time }} ({{ $replay->lap_rank }})</p>

<a href="{{ action('ReplayController@download', compact('replay')) }}">Download</a>
@stop